name: Test Suite

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install SQLite dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsqlite3-dev build-essential
      
      - name: Install server dependencies
        working-directory: ./server
        run: |
          npm ci
          npm rebuild sqlite3 --build-from-source
      
      - name: Install client dependencies
        working-directory: ./client
        run: npm ci
      
      - name: Run server unit tests
        working-directory: ./server
        run: npm test -- --coverage
        env:
          NODE_ENV: test
          REDIS_URL: redis://localhost:6379
      
      - name: Run client unit tests
        working-directory: ./client
        run: npm test -- --coverage
      
      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          files: ./server/coverage/lcov.info,./client/coverage/lcov.info
          flags: unittests
          name: codecov-umbrella

  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install SQLite dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsqlite3-dev build-essential
      
      - name: Install dependencies
        run: |
          cd server
          npm ci
          npm rebuild sqlite3 --build-from-source
          cd ../client
          npm ci
      
      - name: Run integration tests
        working-directory: ./server
        run: npm run test:integration
        env:
          NODE_ENV: test
          REDIS_URL: redis://localhost:6379

  docker-test:
    runs-on: ubuntu-latest
    needs: unit-tests
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
      
      - name: Build Docker image
        run: docker build -t album-finder:test .
      
      - name: Run Docker container
        run: |
          docker compose up -d
          echo "Waiting for services to start..."
          sleep 15
      
      - name: Wait for application health
        run: |
          echo "Checking application health..."
          for i in {1..30}; do
            if curl -f http://localhost:3001/healthz; then
              echo "✅ Application is healthy"
              exit 0
            fi
            echo "⏳ Waiting for application... attempt $i/30"
            sleep 2
          done
          echo "❌ Application failed to become healthy"
          echo "Docker logs:"
          docker compose logs app
          exit 1
      
      - name: Run smoke tests
        run: npm run test:smoke
        env:
          BASE_URL: http://localhost:3001
      
      - name: Upload Playwright report on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-test-report
          path: playwright-report/
          retention-days: 7
      
      - name: Show container logs on failure
        if: failure()
        run: |
          echo "=== App Container Logs ==="
          docker compose logs app
          echo "=== Redis Container Logs ==="
          docker compose logs redis
      
      - name: Cleanup
        if: always()
        run: docker compose down -v

  security-scan:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Run npm audit
        run: |
          cd server && npm audit --audit-level=moderate --omit=dev || true
          cd ../client && npm audit --audit-level=moderate --omit=dev || true
